/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-06-10 07:11:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1654844975311L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1654844975315L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("	");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"UTF-8\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\"\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.88.1\">\n");
      out.write("<title>mocar</title>\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("	\n");
      out.write("	<style>\n");
      out.write("		.nav-link:hover {\n");
      out.write("		    color: #fff;\n");
      out.write("		    background-color: #0d6efd;\n");
      out.write("	  	}  \n");
      out.write("	</style>\n");
      out.write("	\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<main>\n");
      out.write("	<div class=\"row g-0 align-items-start clearfix\">\n");
      out.write("		<div class=\"d-flex flex-column flex-shrink-0 p-3 bg-light order-first\"\n");
      out.write("			style=\"width: 280px; height: 100vh;\">\n");
      out.write("			<a href=\"/\"\n");
      out.write("				class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none\">\n");
      out.write("				<span class=\"fs-4\">Logo</span>\n");
      out.write("			</a>\n");
      out.write("			<hr>\n");
      out.write("			<ul class=\" nav nav-pills flex-column mb-auto\" id=\"navbarToggler8\">\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-dark\" aria-current=\"page\"> 렌트예약 </a></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-dark\"> 공지사항 </a></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-dark\"> Q&amp;A </a></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-dark\"> 찾아오시는 길 </a></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-dark\"> Contact </a></li>\n");
      out.write("			</ul>\n");
      out.write("			<hr>\n");
      out.write("\n");
      out.write("			<a href=\"#\"\n");
      out.write("				class=\"d-flex align-items-center link-dark text-decoration-none\"\n");
      out.write("				id=\"dropdownUser2\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("			</a>\n");
      out.write("			<button type=\"button\" class=\"btn d-flex\" data-bs-toggle=\"modal\"\n");
      out.write("				data-bs-target=\"#staticBackdrop\">\n");
      out.write("				<strong>login</strong>\n");
      out.write("			</button>\n");
      out.write("\n");
      out.write("			<!-- Modal -->\n");
      out.write("			<div class=\"modal fade\" id=\"staticBackdrop\" data-bs-backdrop=\"static\"\n");
      out.write("				data-bs-keyboard=\"false\" tabindex=\"-1\"\n");
      out.write("				aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
      out.write("				<div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("					<div class=\"modal-content\">\n");
      out.write("						<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("							<h2 class=\"fw-bold mb-0\">login</h2>\n");
      out.write("							<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("								aria-label=\"Close\"></button>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"modal-body p-5 pt-0\">\n");
      out.write("							<form class=\"\">\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"email\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"floatingInput\" placeholder=\"name@example.com\"> <label\n");
      out.write("										for=\"floatingInput\">아이디</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"password\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"floatingPassword\" placeholder=\"Password\"> <label\n");
      out.write("										for=\"floatingPassword\">비밀번호</label>\n");
      out.write("								</div>\n");
      out.write("								<button class=\"w-100 mb-2 btn btn-lg rounded-4 btn-primary\"\n");
      out.write("									type=\"submit\">로그인</button>\n");
      out.write("								<hr class=\"my-4\">\n");
      out.write("								<h2 class=\"fs-5 fw-bold mb-3\">다른 방법으로 로그인하기</h2>\n");
      out.write("								<button\n");
      out.write("									class=\"w-100 py-2 mb-2 btn btn-outline-success rounded-4\"\n");
      out.write("									type=\"submit\">\n");
      out.write("									<svg class=\"bi me-1\" width=\"16\" height=\"16\">\n");
      out.write("										<use xlink:href=\"#twitter\" /></svg>\n");
      out.write("									네이버로 로그인하기\n");
      out.write("								</button>\n");
      out.write("								<button\n");
      out.write("									class=\"w-100 py-2 mb-2 btn btn-outline-primary rounded-4\"\n");
      out.write("									type=\"submit\">\n");
      out.write("									<svg class=\"bi me-1\" width=\"16\" height=\"16\">\n");
      out.write("										<use xlink:href=\"#facebook\" /></svg>\n");
      out.write("									페이스북으로 로그인하기\n");
      out.write("								</button>\n");
      out.write("								<button\n");
      out.write("									class=\"w-100 py-2 mb-2 btn btn-outline-warning rounded-4\"\n");
      out.write("									type=\"submit\">\n");
      out.write("									<svg class=\"bi me-1\" width=\"16\" height=\"16\">\n");
      out.write("										<use xlink:href=\"#github\" /></svg>\n");
      out.write("									카카오톡으로 로그인하기\n");
      out.write("								</button>\n");
      out.write("							</form>\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>");
      out.write("\n");
      out.write("	\n");
      out.write("	<div id=\"carouselExampleIndicators\" class=\"carousel slide col\"\n");
      out.write("		data-bs-ride=\"carousel\">\n");
      out.write("		<div class=\"carousel-indicators\">\n");
      out.write("			<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\n");
      out.write("			<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\n");
      out.write("			<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"carousel-inner\">\n");
      out.write("			<div class=\"carousel-item active\">\n");
      out.write("				<img src=\"img/mvis.jpg\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"carousel-item\">\n");
      out.write("				<img src=\"img/mvis1.jpg\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"carousel-item\">\n");
      out.write("				<img src=\"img/mvis2.jpg\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\" text-start carousel-caption d-md-block \" style=\"bottom:13rem;\">\n");
      out.write("		        <h2 class = \"text-shadow-sm\" style=\"text-shadow: 4px 3px 4px rgb(0 0 0 / 50%);\">싸고 편리한 렌트카, 청결하고 쾌적한 차량</h2>\n");
      out.write("		        <h1 style=\"text-shadow: 4px 3px 4px rgb(0 0 0 / 50%);\"><strong>MO CAR</strong></h1>\n");
      out.write("		        <h4 style=\"text-shadow: 4px 3px 4px rgb(0 0 0 / 50%);\">언제나 함께하세요 차량 렌트는 Mo car</h4>\n");
      out.write("	      	</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\n");
      out.write("			<span class=\"carousel-control-prev-icon w-25 h-25\" aria-hidden=\"true\"></span>\n");
      out.write("			<span class=\"visually-hidden\">Previous</span>\n");
      out.write("		</button>\n");
      out.write("		<button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\n");
      out.write("			<span class=\"carousel-control-next-icon w-25 h-25\" aria-hidden=\"true\"></span> \n");
      out.write("			<span class=\"visually-hidden\">Next</span>\n");
      out.write("		</button>\n");
      out.write("	</div>\n");
      out.write(" </div>	\n");
      out.write("	\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js\" integrity=\"sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
