/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-06-28 12:47:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.border;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/border/footer.jsp", Long.valueOf(1655962638281L));
    _jspx_dependants.put("/border/header.jsp", Long.valueOf(1655962638285L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1655181722973L));
    _jspx_dependants.put("jar:file:/C:/0900_GB_YWC/jsp/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp20/wtpwebapps/Project_board/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"UTF-8\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\"\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.88.1\">\n");
      out.write("<title>mocar</title>\n");
      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css\" />\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".nav-link:hover {\n");
      out.write("	color: #fff;\n");
      out.write("	background-color: #0d6efd;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#slider {\n");
      out.write("	width: 50%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#slideList>p {\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css\"\n");
      out.write("	integrity=\"sha256-p6xU9YulB7E2Ic62/PX+h59ayb3PBJ0WFTEQxq0EjHw=\"\n");
      out.write("	crossorigin=\"anonymous\" />\n");
      out.write("<script\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js\"\n");
      out.write("	integrity=\"sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<script>\n");
      out.write("	$(document).ready(function() {\n");
      out.write("		var imgList = $('#slideList p');\n");
      out.write("\n");
      out.write("		$('#slider').slider({\n");
      out.write("			min : 0,\n");
      out.write("			max : 119,\n");
      out.write("			value : 1,\n");
      out.write("			slide : function(event, ui) {\n");
      out.write("				imgList.hide();\n");
      out.write("				imgList.eq(ui.value).show();\n");
      out.write("			}\n");
      out.write("\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	\n");
      out.write("\n");
      out.write("	\n");
      out.write("\n");
      out.write("	<div class=\"row g-0\">\n");
      out.write("		<div\n");
      out.write("			class=\"d-flex flex-column p-3 bg-light order-first col-md-3 col-lg-2\">\n");
      out.write("			<a href=\"/mocar/index.jsp\"\n");
      out.write("				class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none\">\n");
      out.write("				<span class=\"fs-4\">Logo</span>\n");
      out.write("			</a>\n");
      out.write("			<hr>\n");
      out.write("			<ul class=\" nav nav-pills flex-column\" id=\"navbarToggler8\">\n");
      out.write("				<li class=\"nav-item\"><a href=\"/mocar/rent2.jsp\"\n");
      out.write("					class=\"nav-link link-dark\" aria-current=\"page\"> 렌트예약 </a></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"/mocar/border.jsp\"\n");
      out.write("					class=\"nav-link link-dark\"> 공지사항 </a></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"/mocar/BBS.jsp\"\n");
      out.write("					class=\"nav-link link-dark\"> Q&amp;A </a></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"/mocar/map.jsp\"\n");
      out.write("					class=\"nav-link link-dark\"> 찾아오시는 길 </a></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"/mocar/contact.jsp\"\n");
      out.write("					class=\"nav-link link-dark\"> Contact </a></li>\n");
      out.write("			</ul>\n");
      out.write("			<hr>\n");
      out.write("\n");
      out.write("			<a href=\"#\"\n");
      out.write("				class=\"d-flex align-items-center link-dark text-decoration-none\"\n");
      out.write("				id=\"dropdownUser2\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("			</a>\n");
      out.write("			<button type=\"button\" class=\"btn d-flex\" data-bs-toggle=\"modal\"\n");
      out.write("				data-bs-target=\"#login\">\n");
      out.write("				<strong>login</strong>\n");
      out.write("			</button>\n");
      out.write("\n");
      out.write("			<!-- 로그인 -->\n");
      out.write("			<div class=\"modal\" id=\"login\" data-bs-backdrop=\"static\"\n");
      out.write("				data-bs-keyboard=\"false\" tabindex=\"-1\"\n");
      out.write("				aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
      out.write("				<div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("					<div class=\"modal-content\">\n");
      out.write("						<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("							<h2 class=\"fw-bold mb-0\">login</h2>\n");
      out.write("							<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("								aria-label=\"Close\"></button>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"modal-body p-5 pt-0\">\n");
      out.write("							<form name=\"loginForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mocar/login.mc\" method=\"post\">\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"test\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"floatingInput\" placeholder=\"id\" name=\"userid\"> <label\n");
      out.write("										for=\"floatingInput\">아이디</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"password\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"floatingPassword\" placeholder=\"Password\" name=\"userpw\"> <label\n");
      out.write("										for=\"floatingPassword\">비밀번호</label>\n");
      out.write("								</div>\n");
      out.write("								<button class=\"w-100 mb-2 btn btn-lg rounded-4 btn-primary\"\n");
      out.write("									type=\"submit\">로그인</button>\n");
      out.write("								<div id=\"opt\" class=\"row\">\n");
      out.write("									<div class=\"opt_left col\">\n");
      out.write("										<a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#resist\">회원가입</a>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"opt_right col text-end \">\n");
      out.write("										<a id=\"find1\" class=\"d-inline-block \" href=\"#\"\n");
      out.write("											data-bs-toggle=\"modal\" data-bs-target=\"#modalSignin\">ID</a>\n");
      out.write("										<p class=\"d-inline-block\">/</p>\n");
      out.write("										<a id=\"find2\" class=\"d-inline-block\" href=\"#\"\n");
      out.write("											data-bs-toggle=\"modal\" data-bs-target=\"#modalSignpw\">PW찾기</a>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<hr class=\"my-4\">\n");
      out.write("								<h2 class=\"fs-5 fw-bold mb-3\">다른 방법으로 로그인하기</h2>\n");
      out.write("								<button\n");
      out.write("									class=\"w-100 py-2 mb-2 btn btn-outline-success rounded-4\"\n");
      out.write("									type=\"button\" onclick=\"location.href='https://nid.naver.com/'\">\n");
      out.write("									<img src=img/naver.png style=\"width: 20px; height: 20px;\">\n");
      out.write("									네이버로 로그인하기\n");
      out.write("								</button>\n");
      out.write("							</form>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- 회원가입 -->\n");
      out.write("			<div class=\"modal\" id=\"resist\" data-bs-backdrop=\"static\"\n");
      out.write("				data-bs-keyboard=\"false\" tabindex=\"-1\"\n");
      out.write("				aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
      out.write("				<div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("					<div class=\"modal-content\">\n");
      out.write("						<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("							<h2 class=\"fw-bold mb-0\">회원가입</h2>\n");
      out.write("							<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("								aria-label=\"Close\"></button>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"modal-body p-5 pt-0\">\n");
      out.write("							<form name=\"joinForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mocar/index.mc\" method=\"post\">\n");
      out.write("								<div class=\"form-floating row\"\n");
      out.write("									style='width: 100%; margin-left: 1px;'>\n");
      out.write("									<input type=\"text\" class=\"form-control rounded-4 col\"\n");
      out.write("										id=\"floatingInput\" placeholder=\"name@example.com\"\n");
      out.write("										name=\"userid\"> <label for=\"floatingInput\">아이디</label>\n");
      out.write("									<button type=\"button\" class=\"btn btn-primary col-3\"\n");
      out.write("										style='margin-left: 20px;' value=\"중복확인\"\n");
      out.write("										onclick=\"checkId(joinForm.userid.value)\">중복확인</button>\n");
      out.write("									<p id=\"text\"></p>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"password\" class=\"form-control rounded-4\" \n");
      out.write("										id=\"userPw\" placeholder=\"Password\" name=\"userpw\">\n");
      out.write("									<label for=\"floatingPassword\">비밀번호 (8자이상)</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"password\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"userPw_ch\" placeholder=\"Password\" name=\"userpw_ch\">\n");
      out.write("										<font id=\"chkNotice\" size=\"2\"></font>\n");
      out.write("									<label for=\"floatingPassword\">비밀번호 확인</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"text\" class=\"form-control rounded-4 \"\n");
      out.write("										id=\"join_name\" placeholder=\"name\" name=\"username\">\n");
      out.write("										<font id=\"chkName\" size=\"2\"></font>\n");
      out.write("									<label for=\"floatingInput\">이름</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"container px-1\">\n");
      out.write("									<div class=\"row gx-5\">\n");
      out.write("										<div class=\"col\">\n");
      out.write("											<select class=\"form-select\"\n");
      out.write("												aria-label=\"Default select example\" name=\"year\">\n");
      out.write("												<option value=\"none\">선택</option>\n");
      out.write("												");

													for (int i = 2022; i > 1950; i--) {
												
      out.write("\n");
      out.write("												<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("년\n");
      out.write("												</option>\n");
      out.write("												");

													}
												
      out.write("\n");
      out.write("											</select>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"col\">\n");
      out.write("											<select class=\"form-select text-end\"\n");
      out.write("												aria-label=\"Default select example\" name=\"month\">\n");
      out.write("												<option value=\"none\">선택</option>\n");
      out.write("												");

													for (int i = 1; i < 13; i++) {
												
      out.write("\n");
      out.write("												<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("월\n");
      out.write("												</option>\n");
      out.write("												");

													}
												
      out.write("\n");
      out.write("											</select>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"col\">\n");
      out.write("											<select class=\"form-select text-end\"\n");
      out.write("												aria-label=\"Default select example\" name=\"day\">\n");
      out.write("												<option value=\"none\">선택</option>\n");
      out.write("												");

													for (int i = 1; i < 31; i++) {
												
      out.write("\n");
      out.write("												<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("일\n");
      out.write("												</option>\n");
      out.write("												");

													}
												
      out.write("\n");
      out.write("											</select>\n");
      out.write("										</div>\n");
      out.write("\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-3\" style='margin-top: 13px;'>\n");
      out.write("									<input type=\"email\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"email_ch\" placeholder=\"email\" name=\"usermail\">\n");
      out.write("										<font id=\"chkEmail\" size=\"2\"></font>\n");
      out.write("									<label for=\"floatingemail\">이메일</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-3 row\"\n");
      out.write("									style='width: 100%; margin-left: 1px;'>\n");
      out.write("									<input type=\"text\" class=\"form-control rounded-4 col\"\n");
      out.write("										id=\"floatingInput\" placeholder=\"abcd1234\" name=\"usermember\">\n");
      out.write("									<label for=\"floatingInput\">추천인</label>\n");
      out.write("									<button type=\"button\" class=\"btn btn-primary col-3\"\n");
      out.write("										style='margin-left: 20px;'>확인</button>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form\">\n");
      out.write("									<label class=\"\"\n");
      out.write("										style='font-weight: 500; font-size: 18px; margin-bottom: 5px;'>약관\n");
      out.write("										동의</label>\n");
      out.write("									<div class=\"form-checkbox\">\n");
      out.write("										<input class=\"form-check-input\" type=\"checkbox\" value=\"\"\n");
      out.write("											id=\"flexCheckDefault\"> <label\n");
      out.write("											class=\"form-check-label\" for=\"flexCheckDefault\"> </label> <a\n");
      out.write("											class=\"fw-bold\" href=\"#\">이용약관</a>에 동의합니다.\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"modal-footer border-0 p-0 mt-4\">\n");
      out.write("									<button type=\"button\" class=\"btn btn-primary\" value=\"확인\" id=\"join-btn\"\n");
      out.write("										onclick=\"sendit()\">가입</button>\n");
      out.write("									<button type=\"button\" class=\"btn btn-warning\"\n");
      out.write("										data-bs-dismiss=\"modal\">취소</button>\n");
      out.write("								</div>\n");
      out.write("							</form>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- id찾기 -->\n");
      out.write("			<div class=\"modal\" id=\"modalSignin\" data-bs-backdrop=\"static\"\n");
      out.write("				data-bs-keyboard=\"false\" tabindex=\"-1\"\n");
      out.write("				aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
      out.write("				<div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("					<div class=\"modal-content rounded-5 shadow\">\n");
      out.write("						<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("							<h2 class=\"fw-bold mb-0\">ID찾기</h2>\n");
      out.write("							<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("								aria-label=\"Close\"></button>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"modal-body p-5 pt-0\">\n");
      out.write("							<form class=\"\">\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"text\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"floatingInput\" placeholder=\"홍길동\"> <label\n");
      out.write("										for=\"floatingInput\">이름</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"email\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"floatingInput\" placeholder=\"name@example.com\"> <label\n");
      out.write("										for=\"floatingInput\">이메일</label>\n");
      out.write("								</div>\n");
      out.write("							</form>\n");
      out.write("							<div class=\"text-end\">\n");
      out.write("								<button type=\"button\" class=\"btn btn-primary text-end\">확인</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- pw찾기 -->\n");
      out.write("			<div class=\"modal\" id=\"modalSignpw\" data-bs-backdrop=\"static\"\n");
      out.write("				data-bs-keyboard=\"false\" tabindex=\"-1\"\n");
      out.write("				aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
      out.write("				<div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("					<div class=\"modal-content rounded-5 shadow\">\n");
      out.write("						<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("							<h2 class=\"fw-bold mb-0\">PW찾기</h2>\n");
      out.write("							<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("								aria-label=\"Close\"></button>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"modal-body p-5 pt-0\">\n");
      out.write("							<form class=\"\">\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"text\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"floatingInput\" placeholder=\"홍길동\"> <label\n");
      out.write("										for=\"floatingInput\">이름</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-3\">\n");
      out.write("									<input type=\"text\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"floatingInput\" placeholder=\"abcd1234\"> <label\n");
      out.write("										for=\"floatingInput\">아이디</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating mb-5\">\n");
      out.write("									<input type=\"email\" class=\"form-control rounded-4\"\n");
      out.write("										id=\"floatingInput\" placeholder=\"abcd1234\"> <label\n");
      out.write("										for=\"floatingInput\">이메일</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"row g-2 mb-5\">\n");
      out.write("									<div class=\"col-md\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"password\" class=\"form-control\"\n");
      out.write("												id=\"floatingInputGrid\" placeholder=\"password\"> <label\n");
      out.write("												for=\"floatingInputGrid\">변경할 비밀번호</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col-md\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"password\" class=\"form-control\"\n");
      out.write("												id=\"floatingInputGrid\" placeholder=\"password\"> <label\n");
      out.write("												for=\"floatingInputGrid\">비밀번호 재입력</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("							</form>\n");
      out.write("							<div class=\"text-end\">\n");
      out.write("								<button type=\"button\" class=\"btn btn-primary text-end\">확인</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>");
      out.write("\n");
      out.write("<main class=\"ms-sm-auto col-md-9 col-lg-10\">\n");
      out.write("<div id=\"carouselExampleIndicators\" class=\"carousel slide\"\n");
      out.write("	data-bs-ride=\"carousel\">\n");
      out.write("	<div class=\"carousel-indicators\">\n");
      out.write("		<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\n");
      out.write("			data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\"\n");
      out.write("			aria-label=\"Slide 1\"></button>\n");
      out.write("		<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\n");
      out.write("			data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\n");
      out.write("		<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\n");
      out.write("			data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"carousel-inner\">\n");
      out.write("		<div class=\"carousel-item active\">\n");
      out.write("			<img src=\"img/mvis.jpg\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("		</div>\n");
      out.write("		<div class=\"carousel-item\">\n");
      out.write("			<img src=\"img/mvis1.jpg\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("		</div>\n");
      out.write("		<div class=\"carousel-item\">\n");
      out.write("			<img src=\"img/mvis2.jpg\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("		</div>\n");
      out.write("		<div class=\" text-start carousel-caption d-md-block \"\n");
      out.write("			style=\"bottom: 13rem;\">\n");
      out.write("			<h3 class=\"text-shadow-sm\"\n");
      out.write("				style=\"text-shadow: 4px 3px 4px rgb(0 0 0/ 50%);\">싸고 편리한 렌트카,\n");
      out.write("				청결하고 쾌적한 차량</h3>\n");
      out.write("			<h2 style=\"text-shadow: 4px 3px 4px rgb(0 0 0/ 50%);\">\n");
      out.write("				<strong>MO CAR</strong>\n");
      out.write("			</h2>\n");
      out.write("			<h5 style=\"text-shadow: 4px 3px 4px rgb(0 0 0/ 50%);\">언제나 함께하세요\n");
      out.write("				차량 렌트는 Mo car</h5>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<button class=\"carousel-control-prev\" type=\"button\"\n");
      out.write("		data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\n");
      out.write("		<span class=\"carousel-control-prev-icon w-25 h-25\" aria-hidden=\"true\"></span>\n");
      out.write("		<span class=\"visually-hidden\">Previous</span>\n");
      out.write("	</button>\n");
      out.write("	<button class=\"carousel-control-next\" style=\"height: 30.5vw;\"\n");
      out.write("		type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\n");
      out.write("		data-bs-slide=\"next\">\n");
      out.write("		<span class=\"carousel-control-next-icon w-25 h-25\" aria-hidden=\"true\"></span>\n");
      out.write("		<span class=\"visually-hidden\">Next</span>\n");
      out.write("	</button>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"carousel\" style=\"margin-bottom:150px;\">\n");
      out.write("	<div class=\"text-center\" style=\"margin: 100px 0;\">\n");
      out.write("		<hr class=\"m-auto text-primary opacity-100 mb-3\"\n");
      out.write("			style=\"width: 10%; height: 3px;\">\n");
      out.write("		<h1>\n");
      out.write("			<strong>CAR ONE INTRODUCTION</strong>\n");
      out.write("		</h1>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"m-auto row\">\n");
      out.write("		<div id=\"slideList\" class=\"col text-center\">\n");
      out.write("			<p style=\"display: block;\">\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00000.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00001.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00002.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00003.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00004.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00005.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00006.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00007.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00008.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00009.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00010.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00011.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00012.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00013.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00014.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00015.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00016.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00017.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00018.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00019.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00020.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00021.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00022.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00023.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00024.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00025.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00026.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00027.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00028.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00029.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00030.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00031.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00032.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00033.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00034.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00035.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00036.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00037.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00038.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00039.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00040.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00041.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00042.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00043.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00044.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00045.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00046.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00047.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00048.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00049.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00050.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00051.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00052.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00053.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00054.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00055.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00056.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00057.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00058.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00059.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00060.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00061.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00062.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00063.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00064.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00065.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00066.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00067.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00068.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00069.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00070.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00071.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00072.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00073.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00074.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00075.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00076.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00077.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00078.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00079.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00080.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00081.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00082.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00083.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00084.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00085.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00086.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00087.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00088.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00089.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00090.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00091.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00092.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00093.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00094.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00095.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00096.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00097.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00098.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00099.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00100.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00101.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00102.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00103.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00104.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00105.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00106.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00107.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00108.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00109.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00110.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00111.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00112.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00113.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00114.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00115.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00116.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00117.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00118.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				<img src=\"slideImg/Picanto_Green_00119.jpg\" alt=\"\" />\n");
      out.write("			</p>\n");
      out.write("			<div id=\"slider\" class=\"m-auto\"></div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col\">\n");
      out.write("			<h1 class=\"mt-5 pt-5 fw-bold\">\n");
      out.write("				업체 중 <span class=\"text-primary\">최저 가격</span>,\n");
      out.write("			</h1>\n");
      out.write("			<h1 class=\"mt-2 fw-bold\">\n");
      out.write("				<span class=\"text-primary\">차량을</span> 한눈에!\n");
      out.write("			</h1>\n");
      out.write("			<h5 class=\"mt-5\">\n");
      out.write("				Mocar는 고객분들을 위해 실제 차량 이미지를 고집합니다.<br>\n");
      out.write("				<br>실제사진을 보고 원하시는 차를 예약하세요.\n");
      out.write("			</h5>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"carousel border-top\" style=\"margin-bottom:200px;\">\n");
      out.write("	<div class=\"text-center\" style=\"margin: 100px 0;\">\n");
      out.write("		<hr class=\"m-auto text-primary opacity-100 mb-3\"\n");
      out.write("			style=\"width: 10%; height: 3px;\">\n");
      out.write("		<h1>\n");
      out.write("			<strong>COUNSELIN &amp; CONTRACT</strong>\n");
      out.write("		</h1>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"w-75 text-center m-auto row\">\n");
      out.write("		<div class=\"col\">\n");
      out.write("			<img src=\"img/icon1.png\" alt=\"\">\n");
      out.write("			<p class=\"mt-2 fw-bold\">문의하기</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col\">\n");
      out.write("			<img src=\"img/icon2.png\" alt=\"\">\n");
      out.write("			<p class=\"mt-2 fw-bold\">빠른견적</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col\">\n");
      out.write("			<img src=\"img/icon3.png\" alt=\"\">\n");
      out.write("			<p class=\"mt-2 fw-bold\">무서류 심사</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col\">\n");
      out.write("			<img src=\"img/icon4.png\" alt=\"\">\n");
      out.write("			<p class=\"mt-2 fw-bold\">무방문 계약</p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer mt-auto py-3 bg-black\">\r\n");
      out.write("  <div class=\"text-center pt-3\">\r\n");
      out.write("    <p class=\"text-white-50 d-inline-block\">(주)Mocar &nbsp&nbsp</p>\r\n");
      out.write("    <p class=\"text-white-50 d-inline-block\">주소: 서울 강남구 테헤란로 146 &nbsp&nbsp</p>\r\n");
      out.write("    <p class=\"text-white-50 d-inline-block\">사업자등록번호: 010-01-12345 &nbsp&nbsp</p>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"text-center\">\r\n");
      out.write("    <p class=\"text-white-50 d-inline-block\">대표전화: 010-1234-5678 &nbsp&nbsp</p>\r\n");
      out.write("    <p class=\"text-white-50 d-inline-block\">mail: nmjk0123@gmail.com &nbsp&nbsp</p>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"text-center\">\r\n");
      out.write("  	    <p class=\"text-white-50 d-inline-block\">© 2022 Company, Inc &nbsp&nbsp</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script data-cfasync=\"false\" src=\"form-submission-handler.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/momentjs/latest/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js\" integrity=\"sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"user.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /border/header.jsp(67,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.flag }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /border/header.jsp(68,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not param.flag }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<script>\n");
          out.write("				alert(\"로그인에 실패하셨습니다.\");\n");
          out.write("			</script>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /border/header.jsp(74,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.flag2 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /border/header.jsp(75,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not param.flag2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<script>\n");
          out.write("				alert(\"로그인 성공 !!\");\n");
          out.write("			</script>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
